document.addEventListener("DOMContentLoaded",function(){initializePortfolio()});const passiveIfSupported=supportsPassive()?{passive:!0}:!1;function supportsPassive(){let supportsPassive=!1;try{const opts=Object.defineProperty({},'passive',{get:function(){supportsPassive=!0}});window.addEventListener("testPassive",null,opts);window.removeEventListener("testPassive",null,opts)}catch(e){}
return supportsPassive}
function initializePortfolio(){handleLoading();setupNavigation();setupScrollEffects();setupAnimations();setupContactForm();setupBackToTop();setupThemeHandling();if(document.getElementById("resume-modal")){setupResumeModal()}
if(document.querySelector(".typewriter-text")){setTimeout(initTypewriter,500)}}
function handleLoading(){const loader=document.getElementById("loader");window.addEventListener("load",function(){setTimeout(function(){if(loader)loader.classList.add("hidden");setupPageSpecificAnimations()},1200)})}
function setupNavigation(){const mobileMenu=document.getElementById("mobile-menu");const navLinks=document.getElementById("nav-links");const header=document.getElementById("header");if(!mobileMenu||!navLinks||!header)return;mobileMenu.addEventListener("click",function(){toggleMobileMenu(mobileMenu,navLinks)});const navLinkItems=navLinks.querySelectorAll("a");navLinkItems.forEach((link)=>{link.addEventListener("click",function(){closeMobileMenu(mobileMenu,navLinks)})});document.addEventListener("click",function(event){const isClickInsideNav=mobileMenu.contains(event.target)||navLinks.contains(event.target);if(!isClickInsideNav&&navLinks.classList.contains("active")){closeMobileMenu(mobileMenu,navLinks)}});setupSmoothScrolling()}
function toggleMobileMenu(menuButton,navLinks){menuButton.classList.toggle("active");navLinks.classList.toggle("active");const expanded=menuButton.getAttribute("aria-expanded")==="true"||!1;menuButton.setAttribute("aria-expanded",!expanded);document.body.style.overflow=navLinks.classList.contains("active")?"hidden":""}
function closeMobileMenu(menuButton,navLinks){menuButton.classList.remove("active");navLinks.classList.remove("active");menuButton.setAttribute("aria-expanded","false");document.body.style.overflow=""}
function setupSmoothScrolling(){document.querySelectorAll('a[href^="#"]').forEach((anchor)=>{anchor.addEventListener("click",function(e){e.preventDefault();const target=document.querySelector(this.getAttribute("href"));if(target){const headerOffset=80;const elementPosition=target.getBoundingClientRect().top;const offsetPosition=elementPosition+window.pageYOffset-headerOffset;window.scrollTo({top:offsetPosition,behavior:"smooth",})}})})}
function setupScrollEffects(){const header=document.getElementById("header");const sections=document.querySelectorAll(".section");const navLinks=document.querySelectorAll(".nav-links a");if(!header)return;let ticking=!1;window.addEventListener("scroll",function(){if(!ticking){requestAnimationFrame(function(){handleHeaderScroll(header);handleActiveNavigation(sections,navLinks);ticking=!1});ticking=!0}})}
function handleHeaderScroll(header){if(window.scrollY>50){header.classList.add("scrolled")}else{header.classList.remove("scrolled")}}
function handleActiveNavigation(sections,navLinks){if(!sections||!navLinks)return;const scrollPos=window.scrollY+100;sections.forEach((section,index)=>{const top=section.offsetTop;const bottom=top+section.offsetHeight;if(scrollPos>=top&&scrollPos<=bottom){navLinks.forEach((link)=>link.classList.remove("active"));if(navLinks[index]){navLinks[index].classList.add("active")}}})}
function setupAnimations(){const observerOptions={threshold:0.1,rootMargin:"0px 0px -50px 0px",};const observer=new IntersectionObserver(function(entries){entries.forEach((entry)=>{if(entry.isIntersecting){entry.target.classList.add("animate-in");if(entry.target.classList.contains("stagger-animation")){staggerChildAnimations(entry.target)}}})},observerOptions);const animatedElements=document.querySelectorAll(".project-card, .service-card, .skill-category",);animatedElements.forEach((el)=>{el.classList.add("animate-on-scroll");observer.observe(el)})}
function triggerEntranceAnimations(){const heroContent=document.querySelector(".hero-content");if(heroContent){heroContent.classList.add("animate-in")}}
function setupPageSpecificAnimations(){if(document.querySelector(".hero-content")){triggerEntranceAnimations()}}
function staggerChildAnimations(parent){const children=parent.children;Array.from(children).forEach((child,index)=>{setTimeout(()=>{child.classList.add("animate-in")},index*100)})}
function setupContactForm(){const form=document.getElementById("contact-form");if(!form)return;const submitButton=form.querySelector('button[type="submit"]');if(!submitButton)return;setupEmailDomainValidation();form.addEventListener("submit",function(e){e.preventDefault();handleFormSubmission(form,submitButton)});setupFormValidation(form)}
function setupEmailDomainValidation(){const allowedDomains=["gmail.com","yahoo.com","outlook.com","hotmail.com","protonmail.com","icloud.com",];const emailInput=document.getElementById("email");const warning=document.getElementById("email-warning");const form=document.getElementById("contact-form");if(!emailInput||!warning||!form)return;emailInput.addEventListener("input",function(){const email=emailInput.value;const domain=email.substring(email.lastIndexOf("@")+1);if(email&&!allowedDomains.includes(domain)){warning.style.display="block";emailInput.setCustomValidity("Invalid email domain.")}else{warning.style.display="none";emailInput.setCustomValidity("")}});form.addEventListener("submit",function(e){const email=emailInput.value;const domain=email.substring(email.lastIndexOf("@")+1);if(email&&!allowedDomains.includes(domain)){e.preventDefault();warning.style.display="block";showNotification("Submission blocked: Only trusted email domains allowed.","error",);return!1}})}
function handleFormSubmission(form,submitButton){const originalText=submitButton.innerHTML;const formData=new FormData(form);if(!validateForm(form)){showNotification("Please fill in all required fields correctly.","error",);return}
submitButton.innerHTML='<i class="fas fa-spinner fa-spin"></i> Sending...';submitButton.disabled=!0;fetch(form.action,{method:"POST",body:formData,headers:{Accept:"application/json",},}).then((response)=>{if(response.ok){showNotification("Message sent successfully! I'll get back to you soon.","success",);form.reset()}else{throw new Error("Network response was not ok")}}).catch((error)=>{console.error("Error:",error);showNotification("There was a problem sending your message. Please try again later.","error",)}).finally(()=>{submitButton.innerHTML=originalText;submitButton.disabled=!1})}
function setupFormValidation(form){const inputs=form.querySelectorAll("input, textarea");inputs.forEach((input)=>{input.addEventListener("blur",function(){validateField(this)});input.addEventListener("input",function(){clearFieldError(this)})})}
function validateForm(form){const inputs=form.querySelectorAll("input[required], textarea[required]");let isValid=!0;inputs.forEach((input)=>{if(!validateField(input)){isValid=!1}});return isValid}
function validateField(field){const value=field.value.trim();const fieldType=field.type;let isValid=!0;let errorMessage="";if(field.hasAttribute("required")&&!value){isValid=!1;errorMessage="This field is required."}
if(fieldType==="email"&&value){const emailRegex=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;if(!emailRegex.test(value)){isValid=!1;errorMessage="Please enter a valid email address."}}
if(field.name==="name"&&value){const nameRegex=/^[a-zA-Z\s]+$/;if(!nameRegex.test(value)){isValid=!1;errorMessage="Name should only contain letters and spaces."}}
if(!isValid){showFieldError(field,errorMessage)}else{clearFieldError(field)}
return isValid}
function showFieldError(field,message){clearFieldError(field);field.classList.add("error");const errorElement=document.createElement("span");errorElement.className="field-error";errorElement.textContent=message;field.parentNode.appendChild(errorElement)}
function clearFieldError(field){field.classList.remove("error");const existingError=field.parentNode.querySelector(".field-error");if(existingError){existingError.remove()}}
function showNotification(message,type="info"){const notification=document.createElement("div");notification.className=`notification notification-${type}`;notification.innerHTML=`
        <div class="notification-content">
            <i class="fas fa-${getNotificationIcon(type)}"></i>
            <span>${message}</span>
        </div>
        <button class="notification-close">&times;</button>
    `;document.body.appendChild(notification);setTimeout(()=>notification.classList.add("show"),100);setTimeout(()=>hideNotification(notification),5000);notification.querySelector(".notification-close").addEventListener("click",()=>{hideNotification(notification)})}
function hideNotification(notification){notification.classList.add("hide");setTimeout(()=>{if(notification.parentNode){notification.parentNode.removeChild(notification)}},300)}
function getNotificationIcon(type){const icons={success:"check-circle",error:"exclamation-circle",warning:"exclamation-triangle",info:"info-circle",};return icons[type]||icons.info}
function setupBackToTop(){const backToTopButton=document.getElementById("back-to-top");if(!backToTopButton)return;const throttledScrollHandler=throttle(function(){if(window.scrollY>300){backToTopButton.classList.add("visible")}else{backToTopButton.classList.remove("visible")}},16);window.addEventListener("scroll",throttledScrollHandler);backToTopButton.addEventListener("click",function(){window.scrollTo({top:0,behavior:"smooth",})})}
function setupThemeHandling(){const savedTheme=localStorage.getItem("theme")||"dark";document.documentElement.setAttribute("data-theme",savedTheme);window.toggleTheme=function(){const currentTheme=document.documentElement.getAttribute("data-theme");const newTheme=currentTheme==="dark"?"light":"dark";document.documentElement.setAttribute("data-theme",newTheme);localStorage.setItem("theme",newTheme)}}
function debounce(func,wait){let timeout;return function executedFunction(...args){const later=()=>{clearTimeout(timeout);func(...args)};clearTimeout(timeout);timeout=setTimeout(later,wait)}}
function throttle(func,limit){let inThrottle;return function(){const args=arguments;const context=this;if(!inThrottle){func.apply(context,args);inThrottle=!0;setTimeout(()=>(inThrottle=!1),limit)}}}
let scrollTimeout;const optimizedScrollHandler=function(){if(scrollTimeout)return;scrollTimeout=requestAnimationFrame(function(){scrollTimeout=null})};window.addEventListener("scroll",optimizedScrollHandler);window.addEventListener("error",function(e){console.error("JavaScript error:",e.error)});function enhanceAccessibility(){const skipLink=document.createElement("a");skipLink.href="#main-content";skipLink.className="skip-link";skipLink.textContent="Skip to main content";document.body.insertBefore(skipLink,document.body.firstChild);document.addEventListener("keydown",function(e){if(e.key==="Escape"){const mobileMenu=document.getElementById("mobile-menu");const navLinks=document.getElementById("nav-links");if(navLinks&&navLinks.classList.contains("active")){closeMobileMenu(mobileMenu,navLinks)}}})}
document.addEventListener("DOMContentLoaded",enhanceAccessibility);function setupResumeModal(){const resumeModal=document.getElementById("resume-modal");const closeResumeButton=document.getElementById("close-resume");if(!resumeModal||!closeResumeButton)return;closeResumeButton.addEventListener("click",function(){closeResumeModal()});resumeModal.addEventListener("click",function(e){if(e.target===resumeModal){closeResumeModal()}});document.addEventListener("keydown",function(e){if(e.key==="Escape"&&resumeModal.classList.contains("active")){closeResumeModal()}})}
function openResumeModal(){const resumeModal=document.getElementById("resume-modal");if(resumeModal){resumeModal.classList.add("active");document.body.style.overflow="hidden"}}
function closeResumeModal(){const resumeModal=document.getElementById("resume-modal");if(resumeModal){resumeModal.classList.remove("active");document.body.style.overflow=""}}
if(typeof module!=="undefined"&&module.exports){module.exports={validateField,validateForm,showNotification,debounce,throttle,}}
const phrases=["Freelance Data Analyst","Power BI Developer","Excel Dashboard Specialist","Data Cleaning Expert","Python + AI Analyst",];let currentPhrase=0;let currentChar=0;let isDeleting=!1;const typeSpeed=100;const eraseSpeed=50;const delayBetween=1500;function initTypewriter(){const el=document.querySelector(".typewriter-text");if(!el){return}
function type(){const phrase=phrases[currentPhrase];if(!isDeleting){el.textContent=phrase.slice(0,currentChar+1);currentChar++;if(currentChar===phrase.length){isDeleting=!0;setTimeout(type,delayBetween)}else{setTimeout(type,typeSpeed)}}else{el.textContent=phrase.slice(0,currentChar);currentChar--;if(currentChar===0){isDeleting=!1;currentPhrase=(currentPhrase+1)%phrases.length;setTimeout(type,typeSpeed)}else{setTimeout(type,eraseSpeed)}}}
type()}